### ISSUE TITLE
java.io.IOException: Stream closed when resolving Json

### ISSUE THREAD

**Issue by technotic** [novotnyr/spring-jsonschema-validation#1]
I have added the json schema resolver to s Spring REST project but when it processes a request it gets a java.io.IOException: Stream closed exception (few lines from stacktrace below). We are using Spring REST 5.0.5 so did something change from v 4 to cause this? From what I can see the regular RequestBodyArgumentResolver unmarshalls the JSON and then closes the input stream. Any idea for a fix for this?
	at com.github.novotnyr.springframework.web.jsonschema.JsonRequestBodyArgumentResolver.getJsonPayload(JsonRequestBodyArgumentResolver.java:158) ~[spring-jsonschema-validator-0.1-SNAPSHOT.jar:na]
	at com.github.novotnyr.springframework.web.jsonschema.JsonRequestBodyArgumentResolver.validate(JsonRequestBodyArgumentResolver.java:100) ~[spring-jsonschema-validator-0.1-SNAPSHOT.jar:na]
	at com.github.novotnyr.springframework.web.jsonschema.JsonRequestBodyArgumentResolver.resolveArgument(JsonRequestBodyArgumentResolver.java:70) ~[spring-jsonschema-validator-0.1-SNAPSHOT.jar:na]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:124) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:161) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:131) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877) ~[spring-webmvc-5.0.5.RELEASE.jar:5.0.5.RELEASE]

**Comment by novotnyr** [comment]
Usually, this happens when the HttpServletRequest stream has already been consumed by some filter or servlet earlier in the HTTP chain.

One suggestion may be to introduce a HTTP filter that will preserve the HTTP request for multiple InputStream readings.

Spring has `AbstractRequestLoggingFilter` that has a similar philosophy. 

https://github.com/spring-projects/spring-framework/blob/184340ff8ef9aba9510e1c94817cf49cf27bd9bb/spring-web/src/main/java/org/springframework/web/filter/AbstractRequestLoggingFilter.java#L253

**Comment by novotnyr** [comment]
Closing due to inactivity.
